### ISSUE TITLE
Accentuated chars...

### ISSUE THREAD

**Issue by nilopaim** [lupas/vue-keypress#20]
How could I detect accentuated chars? Like "ã", "é", etc...

Currently I receive a deadkey followed by the letter... 

By the way, nice module! All I'm trying to do works, except this issue!

Congrats!

**Comment by lupas** [comment]
Hey @nilopaim 

Sorry for the late response, somehow did not see your issue.

Also accentuated chars have keycodes, you can just check for them being pressed:
e.g. "ä" is 222, "é" is 186, etc.

Test it out here: https://keycode.info/
See table: https://keycode.info/

Hope that works & glad you like the module!

br, Pascal
