### ISSUE TITLE
Question, how can I import this with laravel?

### ISSUE THREAD

**Issue by LasanthaSudeera** [lupas/vue-keypress#25]
I tried to import like this app.js

import Keypres from 'vue-keypress';
window.Keypress = Keypress;

However it didn't seem to import, I tried the component import too like shown, didn't work.

**Comment by lupas** [comment]
I don't see what you want to achieve with doing "window.Keypress", but in your case you have a typo in your example (only one 's')

You have to import vue keypress as a component, however, so the way it's shown in the README should work. Make sure you are in the .vue component file, not in any other file.

You can also try:
```js
import Keypress from 'vue-keypress'

// And then further below
components: {
  Keypress
}
```

**Comment by LasanthaSudeera** [comment]
Thank you. Fixed it.
