### ISSUE TITLE
Is vue-keypress supposed to work with Vue 3?

### ISSUE THREAD

**Issue by niuage** [lupas/vue-keypress#30]
I used this package with nuxt a while ago and liked it. Now I'm trying to use it in a new vue 3 project and I get 

```
[Vue warn]: Invalid VNode type: undefined (undefined) 
  at <Keypress key=0 key-event="keydown" key-code=40  ... >
```

If not, are there any plans to get it to work with Vue 3?

**Comment by lupas** [comment]
Hey @niuage 
Haven't tested it yet but I *assume* that it might **not** work with Vue 3.

I am currently working on a Vue 3 project where I will be needing keypress functionality, so I *might* be updating this module in the coming days or weeks to be working with Vue 3 (or create a vue 3 version for it).

Probably not before the new year, tho.

Feel free to publish a PR if you have time to fix it in the meantime. 👍 

I'll let you know when this is fixed.

BR, Pascal

**Comment by niuage** [comment]
Awesome. Didnt expect to get an answer so soon as well :D

Just fyi, the error I was getting wasn't related to Keypress. What happened is that I missed the fact that async components had to be imported differently than with vue2.

So instead of 

```
components: {
  Keypress: () => import('vue-keypress')
}
```

the new way is, I believe:

```
import { defineAsyncComponent } from 'vue'
...
components: {
      Keypress: defineAsyncComponent(() => import("vue-keypress"))
},
```

That being said, the @success method is still not called, but I'm not getting errors.

**Comment by niuage** [comment]
The code is shorter and more straightforward than I thought. I might just give it a shot :)

edit: I got it somewhat working, I just have an issue with the unbinding the events when the components is unmounted. That part doesn't seem to be working.
edit2: fixed the issue. Not sure how it was working in master tho.

**Comment by niuage** [comment]
https://github.com/lupas/vue-keypress/pull/31/files

This PR is just for index.vue, there's more work to be done on the doc etc, but that'll probably save you a few min :) Do with it what you want!

**Comment by lupas** [comment]
Merged your PR - thanks a lot, worked for me quite well <:o)

Will do some optimisations (docs, demo) and then publish it as `vue3-keypress`, see new repo [here](https://github.com/lupas/vue3-keypress).

Will move your other issue to that repository, so we can track it further.

Thanks for your effort - appreciate it!
Pascal
