### ISSUE TITLE
Override browser behaviour

### ISSUE THREAD

**Issue by LaundroMat** [lupas/vue-keypress#5]
Hi, thanks for this neat component.

I'd like to implement something like what[ tailwindcss.com](https://tailwindcss.com/) does.

![image](https://user-images.githubusercontent.com/42320/77965617-ae8e7080-72e1-11ea-8ac4-2e2cb8163bd1.png)

"/" is a shortcut for the browser's quick search however (at least, that's the case in Firefox). Setting up the component thus:

      <Keypress
        :key-code="58"
        event="keydown"
        @pressed="focusOnSearchInput()"
      />

does not call the method. Is there a way to override the browser behaviour and capture that keypress? 

(I tried the code with other key codes and it works).

**Comment by lupas** [comment]
@LaundroMat 

Does the prevent-default prop work for that?
https://github.com/lupas/vue-keypress#props

**Comment by LaundroMat** [comment]
*slaps forehead*

I completely read over that. Thanks, that works great!
