### ISSUE TITLE
Key press sequences with a superset of modifiers should not trigger the pressed event

### ISSUE THREAD

**Issue by J-Rojas** [lupas/vue-keypress#8]
The modifier check does not filter out key press sequences if more than one specified modifier is pressed.

For example, if I press 'alt' & 'shift', but specified 'alt' as the only modifier for the key event, I would not want the 'pressed' event to occur. These key sequences are not equivalent to one another.

The current code does not treat these sequences differently.

https://github.com/lupas/vue-keypress/blob/0073f85095cf3c0dc090ab1e667fcdf3c9921d8a/src/index.vue#L35

**Comment by lupas** [comment]
Fixed in [v2.0.0](https://github.com/lupas/vue-keypress/releases/tag/v2.0.0)

Thanks a lot @J-Rojas !
